FROM ubuntu:18.04

LABEL maintainer="Mariusz Dolata" \
	  create-date="2019-10-05"
	

RUN apt-get update && apt-get install -y \
	git \
	wget \
	unzip

RUN mkdir /jdk && mkdir /maven

#Maven
RUN wget -q https://mariusz-bucket.s3.eu-central-1.amazonaws.com/resources/apache-maven-3.6.1-bin.zip
RUN unzip apache-maven-3.6.1-bin.zip -d /maven
RUN rm apache-maven-3.6.1-bin.zip
ENV MAVEN_HOME /maven/apache-maven-3.6.1
ENV PATH ${MAVEN_HOME}/bin:${PATH}

#JDK
RUN wget -q https://mariusz-bucket.s3.eu-central-1.amazonaws.com/resources/jdk-12.0.2_linux-x64_bin.tar.gz
RUN tar xvzf jdk-12.0.2_linux-x64_bin.tar.gz -C /jdk
RUN rm jdk-12.0.2_linux-x64_bin.tar.gz
ENV JAVA_HOME /jdk/jdk-12.0.2
ENV PATH ${JAVA_HOME}/bin:${PATH}






